// frappe_docker/tutor-connect-hub/src/components/home/HeroSection.tsx
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Search, ArrowRight, Star } from "lucide-react";
import {
  CrownDoodle,
  LightbulbDoodle,
  FlowerDoodle,
  SunDoodle,
  ScallopEdge,
} from "@/components/ui/doodles";

export function HeroSection() {
  const navigate = useNavigate();

  return (
    <section className="relative overflow-hidden">
      {/* Full-width background photo */}
      <div className="absolute inset-0">
        <img
          src="/images/hero-classroom.jpg"
          alt="Happy pupils raising their hands in a classroom"
          className="h-full w-full object-cover object-center"
        />
        {/* Warm cream overlay for text readability */}
        <div className="absolute inset-0 bg-gradient-to-r from-cream via-cream/85 to-accent-yellow/20" />
        <div className="absolute inset-0 bg-gradient-to-t from-cream/60 via-transparent to-transparent" />
      </div>

      {/* Floating doodles */}
      <CrownDoodle className="absolute left-6 top-10 h-12 w-14 -rotate-12 drop-shadow-md sm:left-16 sm:h-16 sm:w-20" />
      <LightbulbDoodle className="absolute right-8 top-16 h-14 w-14 rotate-12 drop-shadow-md sm:right-24 sm:h-20 sm:w-20" />
      <FlowerDoodle className="absolute bottom-24 left-6 h-14 w-14 rotate-6 drop-shadow-md sm:bottom-32 sm:left-24 sm:h-20 sm:w-20" />
      <SunDoodle className="absolute bottom-24 right-8 h-16 w-16 drop-shadow-md sm:bottom-40 sm:right-40 sm:h-24 sm:w-24" />

      <div className="relative mx-auto max-w-7xl px-4 pb-28 pt-16 sm:px-6 sm:pb-36 sm:pt-24 lg:px-8">
        <div className="max-w-2xl">
          <div className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-extrabold text-primary-600 shadow-md border-2 border-primary-200 mb-6">
            <Star className="h-4 w-4 fill-accent-yellow text-accent-yellow" />
            Trusted by 500+ students
          </div>

          <h1 className="text-4xl font-black tracking-tight text-foreground sm:text-6xl lg:text-7xl leading-[1.08]">
            Find the Perfect{" "}
            <span className="relative inline-block text-primary-500">
              Tutor
              <svg
                viewBox="0 0 220 20"
                aria-hidden="true"
                className="absolute -bottom-2 left-0 w-full"
              >
                <path
                  d="M4,14 C50,4 120,4 216,12"
                  fill="none"
                  stroke="#FF8C42"
                  strokeWidth="7"
                  strokeLinecap="round"
                />
              </svg>
            </span>{" "}
            for Your Learning Journey
          </h1>

          <p className="mt-6 max-w-xl text-lg font-semibold text-foreground/70 sm:text-xl leading-relaxed">
            Connect with qualified, experienced tutors in Mathematics, Sciences,
            Languages, and more. Personalized 1-on-1 sessions tailored to your
            learning pace and goals.
          </p>

          <div className="mt-8 flex flex-col gap-4 sm:flex-row">
            <Button size="lg" onClick={() => navigate("/register/student")}>
              <Search className="mr-2 h-5 w-5" />
              Find a Tutor
            </Button>
            <Button size="lg" variant="outline" onClick={() => navigate("/register/tutor")}>
              Become a Tutor
              <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </div>

          <div className="mt-10 flex flex-wrap items-center gap-6">
            <div className="flex items-center gap-3">
              <div className="flex -space-x-3">
                {[
                  "/images/avatar-parent.jpg",
                  "/images/avatar-student.jpg",
                  "/images/avatar-tutor.jpg",
                  "/images/boy-studying.jpg",
                ].map((src, i) => (
                  <img
                    key={i}
                    src={src}
                    alt=""
                    className="h-11 w-11 rounded-full border-[3px] border-white object-cover shadow-md"
                  />
                ))}
              </div>
              <span className="text-sm font-extrabold text-foreground/70">
                +200 active tutors
              </span>
            </div>
            <div className="flex items-center gap-1.5 rounded-full bg-white px-4 py-2 shadow-md border-2 border-accent-yellow">
              <Star className="h-4 w-4 fill-accent-yellow text-accent-yellow" />
              <span className="text-sm font-black text-foreground">4.9/5</span>
              <span className="text-xs font-bold text-muted-foreground">student rating</span>
            </div>
          </div>
        </div>
      </div>

      {/* Enrollment ribbon (Kidza "Admission Open" motif) */}
      <div className="absolute right-6 top-1/2 hidden -translate-y-1/2 rotate-6 lg:block xl:right-24">
        <div className="relative">
          <div className="rounded-2xl bg-primary-500 px-8 py-3 text-center shadow-xl">
            <span className="text-xl font-black tracking-widest text-white">
              ENROLLMENT
            </span>
          </div>
          <div className="mx-auto -mt-1 w-max rounded-2xl bg-secondary-400 px-10 py-3 text-center shadow-xl">
            <span className="text-2xl font-black tracking-widest text-white">OPEN</span>
          </div>
          <div className="absolute -left-6 top-1/2 h-0 w-0 -translate-y-1/2 border-y-[14px] border-r-[24px] border-y-transparent border-r-primary-700" />
        </div>
      </div>

      {/* Scalloped wave bottom into Subjects section (orange) */}
      <div className="absolute bottom-0 left-0 right-0">
        <ScallopEdge fill="#FF8C42" />
      </div>
    </section>
  );
}

// frappe_docker/apps/edu_theme/frontend/src/components/sections/HeroSection.vue
<script setup lang="ts">
import Button from '@/components/ui/button/Button.vue'
import educationHero from '@/assets/education-hero.png'
</script>

<template>
  <section class="relative bg-hero-gradient pt-24 pb-16 md:pt-32 md:pb-24 overflow-hidden">
    <!-- Background Pattern -->
    <div class="absolute inset-0 opacity-10">
      <div class="absolute top-20 left-10 w-32 h-32 rounded-full bg-primary-foreground/20" />
      <div class="absolute bottom-20 right-20 w-48 h-48 rounded-full bg-primary-foreground/10" />
      <div class="absolute top-1/2 left-1/3 w-24 h-24 rounded-full bg-primary-foreground/15" />
    </div>

    <div class="container-section relative z-10">
      <div class="grid lg:grid-cols-2 gap-12 items-center">
        <!-- Content -->
        <div
          v-motion
          :initial="{ opacity: 0, x: -30 }"
          :enter="{ opacity: 1, x: 0, transition: { duration: 600 } }"
          class="text-center lg:text-left"
        >
          <p class="text-primary-foreground/80 text-sm font-semibold tracking-widest uppercase mb-4">
            Welcome to the Future of Learning
          </p>
          <h1 class="text-4xl md:text-5xl lg:text-6xl font-bold text-primary-foreground leading-tight mb-6">
            Empowering Minds
            <span class="block">
              Shaping
              <span class="text-yellow">Tomorrow</span>
            </span>
          </h1>
          <p class="text-primary-foreground/80 text-lg mb-8 max-w-lg mx-auto lg:mx-0">
            Welcome to our innovative education portal. Manage your curriculum,
            track progress, and access resources through our seamless digital campus.
          </p>
          <div class="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
            <Button variant="accent" size="lg">
              Get Started Now
            </Button>
            <Button variant="heroOutline" size="lg">
              Learn More
            </Button>
          </div>
        </div>

        <!-- Hero Image -->
        <div
          v-motion
          :initial="{ opacity: 0, x: 30 }"
          :enter="{ opacity: 1, x: 0, transition: { duration: 600, delay: 200 } }"
          class="relative flex justify-center lg:justify-end"
        >
          <div class="relative">
            <img
              :src="educationHero"
              alt="Education illustration with books, graduation cap, and learning tools"
              class="w-full max-w-md lg:max-w-lg drop-shadow-2xl"
              v-motion
              :enter="{ y: [0, -10, 0], transition: { duration: 3000, repeat: Infinity, ease: 'easeInOut' } }"
            >
            <!-- Floating badge -->
            <div
              class="absolute -bottom-4 -right-4 bg-card px-4 py-2 rounded-lg shadow-lg"
              v-motion
              :initial="{ opacity: 0, scale: 0.8 }"
              :enter="{ opacity: 1, scale: 1, transition: { delay: 800 } }"
            >
              <p class="text-sm font-semibold text-foreground">
                🎓 Join 2000+ Students
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Wave divider -->
    <div class="absolute bottom-0 left-0 right-0">
      <svg
        viewBox="0 0 1440 120"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        class="w-full"
        preserveAspectRatio="none"
      >
        <path
          d="M0 120L60 110C120 100 240 80 360 70C480 60 600 60 720 65C840 70 960 80 1080 85C1200 90 1320 90 1380 90L1440 90V120H1380C1320 120 1200 120 1080 120C960 120 840 120 720 120C600 120 480 120 360 120C240 120 120 120 60 120H0V120Z"
          fill="hsl(var(--background))"
        />
      </svg>
    </div>
  </section>
</template>
