// frappe_docker/new_vue_website_for_reference2/src/components/Header.vue
<script setup lang="ts">
import Button from '@/components/ui/Button.vue'

const navLinks = [
  { name: "Home", href: "#" },
  { name: "Courses", href: "#courses" },
  { name: "Admissions", href: "#admissions" },
  { name: "News", href: "#news" },
  { name: "Contact", href: "#contact" },
]
</script>

<template>
  <header class="sticky top-0 z-50 w-full bg-hero/95 backdrop-blur-sm">
      <div class="container mx-auto flex h-20 items-center justify-between px-6">
        <!-- Logo -->
        <div class="flex items-center gap-2">
          <span class="rounded-lg bg-vanilla-custard px-3 py-1.5 font-gemola text-xl font-bold text-ink-black">
            EDUCLO
          </span>
        </div>

        <!-- Navigation -->
        <nav class="hidden items-center gap-8 md:flex">
          <a
            v-for="link in navLinks"
            :key="link.name"
            :href="link.href"
            class="font-raleway text-sm font-medium uppercase tracking-wider text-hero-foreground/80 transition-colors hover:text-hero-foreground"
          >
            {{ link.name }}
          </a>
        </nav>

        <!-- Auth Buttons -->
        <div class="flex items-center gap-4">
          <Button variant="ghost" class="text-hero-foreground hover:bg-hero-foreground/10">
            Login
          </Button>
          <Button variant="hero" size="default">
            Desk
          </Button>
        </div>
      </div>
    </header>
</template>

// frappe_docker/apps/tutor_hub/frontend/src/components/layout/Header.tsx
// Scroll-anchor navigation — no react-router, no page reloads.
// All hrefs point to #section-id anchors defined in App.tsx.

export default function Header() {
  const handleAnchorClick = (e: React.MouseEvent<HTMLAnchorElement>, href: string) => {
    if (href.startsWith("#")) {
      e.preventDefault();
      document.querySelector(href)?.scrollIntoView({ behavior: "smooth" });
    }
  };

  return (
    <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container flex h-16 items-center justify-between">
        <a href="#home" className="flex items-center gap-2 font-bold text-xl font-serif">
          <span className="text-primary">Tutor</span>Hub
        </a>

        <nav className="hidden md:flex items-center gap-6 text-sm font-medium">
          {[
            { label: "Find a Tutor", href: "#tutors" },
            { label: "Subjects", href: "#subjects" },
            { label: "How It Works", href: "#how-it-works" },
          ].map(({ label, href }) => (
            <a
              key={href}
              href={href}
              onClick={(e) => handleAnchorClick(e, href)}
              className="text-muted-foreground transition-colors hover:text-foreground"
            >
              {label}
            </a>
          ))}
        </nav>

        <div className="flex items-center gap-3">
          <a
            href="/login"
            className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
          >
            Log In
          </a>
          <a
            href="#tutors"
            onClick={(e) => handleAnchorClick(e, "#tutors")}
            className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow hover:bg-primary/90 transition-colors"
          >
            Get Started
          </a>
        </div>
      </div>
    </header>
  );
}
